### ISSUE TITLE
Adding a search bar 

### ISSUE THREAD

**Issue by jaskirat2000** [sugarlabs/turtleblocksjs#360]
images for this can be seen here :
(https://wiki.sugarlabs.org/images/3/3d/IMAGE.jpg )
( https://wiki.sugarlabs.org/images/f/f1/Image1.jpg 

A search bar that will be placed on the top along with the main toolbar or just above the palette icons . this will be useful for the user to find the blocks. A person can search out the with alphabets. Like if “S” alphabet is written , it will show all the blocks with name starting from “S”.

![im4](https://user-images.githubusercontent.com/10228651/37407404-940784a0-27bf-11e8-9fda-cc181c2edf4a.jpg)

**Comment by walterbender** [comment]
Is the current search bar inadequate? How so?

![screenshot from 2018-03-15 18-39-36](https://user-images.githubusercontent.com/3996641/37494675-4610fe90-2880-11e8-947d-1ab119cf22eb.png)

**Comment by jaskirat2000** [comment]
It would have been placed along with the main toolbar

**Comment by walterbender** [comment]
You did not answer my question. Why move it from its current location?

**Comment by walterbender** [comment]
Search is part of the palette selector now.
