### ISSUE TITLE
link to contribution guidelines not working

### ISSUE THREAD

**Issue by vaibhavdaren** [sugarlabs/turtleblocksjs#393]
the link https://github.com/sugarlabs/sugar-docs/blob/master/contributing.md in https://github.com/sugarlabs/turtleblocksjs#contributing Contributing Guidelines is not working in readme and should be  replaced by new link.

**Comment by vaibhavdaren** [comment]
i think the new link is https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md

**Comment by walterbender** [comment]
Please make a PR with the proper link

**Comment by jaskirat2000** [comment]
@vaibhavdaren yes its not working and this one is fine

**Comment by vaibhavdaren** [comment]
@jaskirat2000  thanks  :+1:
