### ISSUE TITLE
links to following plugins are not working in readme

### ISSUE THREAD

**Issue by vaibhavdaren** [sugarlabs/turtleblocksjs#427]
RoDi
Carbon Calculator
Maths 
Translate 
Dictionary 
Weather 
Logic 
Finance 
Bitcoin 
Nutrition 
Facebook 
Heap 
Accelerometer 
Turtle 
Gmap 
Random quote

Do we have to link them to their JSON file in plugins or they have separate repositories like Mindstorm plugin?

**Comment by walterbender** [comment]
We want to link to the raw JSON files for download.
