### ISSUE TITLE
Suggested feature:adding scrollbar to block windows

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/turtleblocksjs#451]
A scroll bar can be added in place of the navigation buttons.I think it would be more convenient for the users to scroll and select in place of using buttons.
![image](https://user-images.githubusercontent.com/35092582/50493918-544f9180-0a46-11e9-80c4-0f569e5268a4.png)

**Comment by Aniket21mathur** [comment]
@walterbender what are your opinions about  this?

**Comment by walterbender** [comment]
I think it would be nice. But a bit tricky perhaps to implement since the palettes are not implemented in HTML -- they are easel.js objects. The reason for this is so that you can drag blocks from the palettes on to the canvas. There might be a way to do this in HTML, but it would be a major refactoring. But it should be reasonably straight forward to implement a scrollbar-like effect using easel.

**Comment by S-kus** [comment]
I tried it. @walterbender look at this. Will this work?

https://user-images.githubusercontent.com/86892991/147887321-a241539b-3ee4-4129-a417-9b2b6c0635fe.mp4

**Comment by walterbender** [comment]
Looks good. But I am not sure we really need to add this feature.

**Comment by S-kus** [comment]
@walterbender I think it's probably not needed in "Turtle Block", but in "Music Blocks" there are some tabs like "flow", "action" and "widgets" which have more icons. For these tabs and also in case someone using it on small screen devices, it will be more user-friendly if there is a slider.

**Comment by Aniket21mathur** [comment]
Hii @walterbender and @S-kus, hope that you are well. I think it will make sense to have this feature. It will help in improving the UX, as sometimes it's not that intuitive that the window is scrollable. This was the reason I opened this issue. @walterbender what do you think.

**Comment by walterbender** [comment]
As long as it is not invasive, it is fine with me. The new palette design (2020) is more easily modified.

**Comment by S-kus** [comment]
@walterbender I didn't understand it clearly. Could you confirm? Will this issue be closed? or should I raise the pull request?

**Comment by walterbender** [comment]
Feel free to work on this. But unless it is a very simple change, it may not be accepted into the release. (We have a feature freeze in place for v3 of MB.)

**Comment by S-kus** [comment]
Thanks, @walterbender, I will raise the pull request.

**Comment by S-kus** [comment]
@walterbender Please review it. I will fix them if any changes are required.
